Gapura/Controllers/RequestTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gapura.Models;

namespace Gapura.Controllers
{
    public class RequestTypesController : Controller
    {
        private YSIDGAEntitiesConn dbConn = new YSIDGAEntitiesConn();

        //
        // GET: /RequestTypes/

        public ActionResult Index()
        {
            return View(dbConn.MasterRequestTypes.ToList());
        }

        //
        // GET: /RequestTypes/Details/5

        public ActionResult Details(short id = 0)
        {
            MasterRequestType masterrequesttype = dbConn.MasterRequestTypes.Find(id);
            if (masterrequesttype == null)
            {
                return HttpNotFound();
            }
            return View(masterrequesttype);
        }

        //
        // GET: /RequestTypes/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /RequestTypes/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterRequestType masterrequesttype)
        {
            if (ModelState.IsValid)
            {
                dbConn.MasterRequestTypes.Add(masterrequesttype);
                dbConn.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(masterrequesttype);
        }

        //
        // GET: /RequestTypes/Edit/5

        public ActionResult Edit(short id = 0)
        {
            MasterRequestType masterrequesttype = dbConn.MasterRequestTypes.Find(id);
            if (masterrequesttype == null)
            {
                return HttpNotFound();
            }
            return View(masterrequesttype);
        }

        //
        // POST: /RequestTypes/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MasterRequestType masterrequesttype)
        {
            if (ModelState.IsValid)
            {
                dbConn.Entry(masterrequesttype).State = EntityState.Modified;
                dbConn.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(masterrequesttype);
        }

        //
        // GET: /RequestTypes/Delete/5

        public ActionResult Delete(short id = 0)
        {
            MasterRequestType masterrequesttype = dbConn.MasterRequestTypes.Find(id);
            if (masterrequesttype == null)
            {
                return HttpNotFound();
            }
            return View(masterrequesttype);
        }

        //
        // POST: /RequestTypes/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id)
        {
            MasterRequestType masterrequesttype = dbConn.MasterRequestTypes.Find(id);
            dbConn.MasterRequestTypes.Remove(masterrequesttype);
            dbConn.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            dbConn.Dispose();
            base.Dispose(disposing);
        }
    }
}

Gapura/Views/RequestTypes/Create.cshtml
@model Gapura.Models.MasterRequestType

@{
    ViewBag.Title = "Create Request Type";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title>
            <h2><i class="icon-pencil"></i><span
                class="break"></span>Create New Request Type</h2>
            <div class="box-icon">
                @*<a href="~/Products/Index" class="btn-setting"><i class="halflings-icon wrench"></i></a>*@
                <a href="@Url.Action("Index")"
                    title="Return to Index List" >
                    <i class="halflings-icon chevron-up"></i><span class="hidden-tablet"></span>
                </a>
                <a href="~/Home/Index" class="btn-close"
                    title="Return to Homepage">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">

            @using (Html.BeginForm("Create", "RequestTypes", FormMethod.Post, new
        {
            @class = "form-horizontal"
        }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend></legend>

                    <div class="editor-label">
                        @Html.Label("RequestType", "Request Type", new { @class = "control-label" })

                        @Html.EditorFor(model => model.RequestType)
                        @Html.ValidationMessageFor(model => model.RequestType)
                    </div>

                    <div class="editor-label">
                        @Html.Label("RequestNote", "Request Note", new { @class = "control-label" })

                        @Html.EditorFor(model => model.RequestNote)
                        @Html.ValidationMessageFor(model => model.RequestNote)
                    </div>

                    <div class="form-actions">
                        <a class="btn btn-success" href="#" onclick="$('form').submit();">Save</a>
                        <input type="reset" value="Reset" class="btn" />
                        <a href="@Url.Action("Index")" class="btn btn-info">Cancel</a>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<style>
    div.editor-label {
        margin-bottom: 14px !important;
    }
</style>

Gapura/Views/RequestTypes/Delete.cshtml
@model Gapura.Models.MasterRequestType

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>MasterRequestType</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RequestType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RequestType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RequestNote)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RequestNote)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Gapura/Views/RequestTypes/Details.cshtml
@model Gapura.Models.MasterRequestType

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>MasterRequestType</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RequestType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RequestType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RequestNote)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RequestNote)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Gapura/Views/RequestTypes/Edit.cshtml
@model Gapura.Models.MasterRequestType

@{
    ViewBag.Title = "Edit Request Type";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title>
            <h2><i class="icon-edit"></i><span
                class="break"></span>Edit Request Type</h2>
            <div class="box-icon">
                @*<a href="~/Products/Index" class="btn-setting"><i class="halflings-icon wrench"></i></a>*@
                <a href="@Url.Action("Index")"
                    title="Return to Index List" >
                    <i class="halflings-icon chevron-up"></i><span class="hidden-tablet"></span>
                </a>
                <a href="~/Home/Index" class="btn-close"
                    title="Return to Homepage">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">

            @using (Html.BeginForm("Edit", "RequestTypes", FormMethod.Post, new
        {
            @class = "form-horizontal"
        }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend></legend>

                    @Html.HiddenFor(model => model.id)

                    <div class="editor-label">
                        @Html.Label("RequestType", "Request Type", new { @class = "control-label" })

                        @Html.EditorFor(model => model.RequestType)
                        @Html.ValidationMessageFor(model => model.RequestType)
                    </div>

                    <div class="editor-label">
                        @Html.Label("RequestNote", "Request Note", new { @class = "control-label" })

                        @Html.EditorFor(model => model.RequestNote)
                        @Html.ValidationMessageFor(model => model.RequestNote)
                    </div>

                    <div class="form-actions">
                        <a class="btn btn-success" href="#" onclick="$('form').submit();">Save</a>
                        <input type="reset" value="Reset" class="btn" />
                        <a href="@Url.Action("Index")" class="btn btn-info">Cancel</a>
                        <a href="@Url.Action("Delete", new { id = @Html.DisplayFor(model => model.id) })" class="btn btn-danger">Delete</a>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
 }

<style>
    div.editor-label {
        margin-bottom: 14px !important;
    }
</style>

Gapura/Views/RequestTypes/Index.cshtml
@model IEnumerable<Gapura.Models.MasterRequestType>

@{
    ViewBag.Title = "Index of Request Type";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title>
            <h2><i class="icon-table"></i><span
                class="break"></span>Set Up New Request Type</h2>
            <div class="box-icon">
                <a href="@Url.Action("Create", "RequestTypes")">
                    <i class="halflings-icon plus"></i><span class="hidden-tablet"></span>
                    Add New Request Type
                </a>
            </div>
        </div>
        <div class="box-content">

            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.RequestType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.RequestNote)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.RequestType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RequestNote)
                        </td>
                        <td>
                            <a class="btn btn-success"
                                href="@Url.Action("Details", new { id = item.id })">
                                <i class="halflings-icon white zoom-in"></i>
                            </a>
                            <a class="btn btn-info"
                                href="@Url.Action("Edit", new { id = item.id })">
                                <i class="halflings-icon white edit"></i>
                            </a>
                            <a class="btn btn-danger"
                                href="@Url.Action("Delete", new { id = item.id })">
                                <i class="halflings-icon white trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

<style>
    th {
        background-color: #cdcdcd !important;
        border: dotted 1px;
    }
    td {
        border: dotted 1px;
    }
</style>